$ErrorActionPreference = "Stop"

$root = Resolve-Path (Join-Path $PSScriptRoot "..")

function Assert-File {
    param([string]$Path)
    $fullPath = Join-Path $root $Path
    if (-not (Test-Path -LiteralPath $fullPath -PathType Leaf)) {
        throw "Missing expected file: $Path"
    }
}

function Assert-Contains {
    param(
        [string]$Path,
        [string]$Pattern
    )
    $fullPath = Join-Path $root $Path
    $content = Get-Content -LiteralPath $fullPath -Raw -Encoding UTF8
    if ($content -notmatch $Pattern) {
        throw "Expected '$Path' to contain pattern: $Pattern"
    }
}

function Assert-NotContains {
    param(
        [string]$Path,
        [string]$Pattern
    )
    $fullPath = Join-Path $root $Path
    $content = Get-Content -LiteralPath $fullPath -Raw -Encoding UTF8
    if ($content -match $Pattern) {
        throw "Expected '$Path' not to contain pattern: $Pattern"
    }
}

function U {
    param([int[]]$CodePoints)
    -join ($CodePoints | ForEach-Object { [char]$_ })
}

Assert-File "docs\product\android-app-architecture.md"
Assert-File "docs\compatibility.md"
Assert-File "apps\android\settings.gradle.kts"
Assert-File "apps\android\build.gradle.kts"
Assert-File "apps\android\gradle.properties"
Assert-File "apps\android\app\build.gradle.kts"
Assert-File "apps\android\app\src\main\AndroidManifest.xml"
Assert-File "apps\android\app\src\main\res\values\strings.xml"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\MainActivity.kt"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectUiModels.kt"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGatewayFactory.kt"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\permissions\AndroidPermissionGateway.kt"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidStorageGateway.kt"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidPublishWorker.kt"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverServiceController.kt"
Assert-File "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt"
Assert-File "apps\android\README.md"
Assert-File "scripts\install_android_debug.ps1"
Assert-File "scripts\collect_android_diagnostics.ps1"
Assert-File "scripts\smoke_android_device.ps1"
Assert-File "scripts\prepare_android_real_camera_test.ps1"
Assert-File "scripts\inspect_android_apk.ps1"
Assert-File "scripts\preflight_android_device.ps1"
Assert-File "scripts\start_android_emulator.ps1"
Assert-File "scripts\verify_android_emulator_ui.ps1"
Assert-File "scripts\verify_android_emulator_ftp_upload.ps1"

Assert-Contains "apps\android\settings.gradle.kts" "CameraConnectorAndroid"
Assert-Contains "docs\compatibility.md" "Android Physical Device Test Template"
Assert-Contains "docs\compatibility.md" "SAF publish"
Assert-Contains "apps\android\README.md" "docs\\compatibility\.md"
Assert-Contains "docs\superpowers\specs\2026-05-26-storage-model-optimization-design.md" "receiver_accounts"
Assert-Contains "docs\superpowers\specs\2026-05-26-storage-model-optimization-design.md" "There is intentionally no"
Assert-Contains "docs\superpowers\specs\2026-05-26-storage-model-optimization-design.md" "import_sessions"
Assert-Contains "apps\android\build.gradle.kts" "com\.android\.application.*9\.2\.0"
Assert-Contains "apps\android\app\build.gradle.kts" "org\.jetbrains\.kotlin\.plugin\.compose"
Assert-Contains "apps\android\app\build.gradle.kts" "compileSdk = 36"
Assert-Contains "apps\android\app\build.gradle.kts" "USE_NATIVE_CORE"
Assert-Contains "apps\android\app\build.gradle.kts" "androidx\.compose:compose-bom:2026\.05\.00"
Assert-Contains "apps\android\app\build.gradle.kts" "androidx\.documentfile:documentfile"
Assert-Contains "apps\android\app\src\main\AndroidManifest.xml" "android\.permission\.FOREGROUND_SERVICE_DATA_SYNC"
Assert-Contains "apps\android\app\src\main\AndroidManifest.xml" "ReceiverForegroundService"
Assert-Contains "apps\android\app\src\main\AndroidManifest.xml" "@string/app_name"
Assert-Contains "apps\android\app\src\main\res\values\strings.xml" (U @(0x76F8,0x673A,0x8FDE,0x63A5,0x5668))
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\MainActivity.kt" "CoreGatewayFactory\.create"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\MainActivity.kt" "ActivityResultContracts\.RequestPermission"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\MainActivity.kt" "ActivityResultContracts\.OpenDocumentTree"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\MainActivity.kt" "persistInboxDirectory"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\MainActivity.kt" "selectedInboxLabel"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\permissions\AndroidPermissionGateway.kt" "POST_NOTIFICATIONS"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidStorageGateway.kt" "selectedInboxLabel"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidStorageGateway.kt" "SharedPreferences"
Assert-Contains "scripts\verify_android_emulator_ui.ps1" "Tap-UiNodeByText"
Assert-Contains "scripts\verify_android_emulator_ui.ps1" "Use-EmulatorBindableReceiverConfig"
Assert-Contains "scripts\verify_android_emulator_ui.ps1" "ProjectWorkspace"
Assert-Contains "scripts\verify_android_emulator_ui.ps1" "FTP 192\.168\.50\.1:2121"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidStorageGateway.kt" "inbox_uri"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidStorageGateway.kt" "project_photo_grid_columns"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidStorageGateway.kt" "projectPhotoGridColumnCount"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidStorageGateway.kt" "persistProjectPhotoGridColumnCount"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidStorageGateway.kt" "selectedInboxUri"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidPublishWorker.kt" "class AndroidPublishWorker"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidPublishWorker.kt" "FilePublishTarget"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidPublishWorker.kt" "SafPublishTarget"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidPublishWorker.kt" "DocumentTreeStore"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidPublishWorker.kt" "document_uri"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidPublishWorker.kt" "completePublish"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\storage\AndroidPublishWorker.kt" "markPublishFailed"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "notificationPermissionGranted"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "onRequestNotificationPermission"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "selectedInboxLabel"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "onChooseInboxDirectory"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "observeProjects"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "ProjectManagementScreen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectManagementScreen.kt" "ProjectManagementRow"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectManagementScreen.kt" "ProjectGlobalStatusCard"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "projectWorkspaceOpen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "ProjectScopeCard"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "coreGateway\.createProject"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "coreGateway\.setActiveProject"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "actionError"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "actionInFlight"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "actionsEnabled"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "runAction"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "finally"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "try"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "onClearActionError"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\AccountsScreen.kt" "PasswordVisualTransformation"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\AccountsScreen.kt" "OutlinedTextField"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "Icons\.Outlined\.Settings"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "SettingsScreen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "AccountDetailScreen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectReceiverControls.kt" "PowerButton"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectReceiverControls.kt" "ProtocolSegment"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "InboxFilterBar"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "ScoreFilterBar"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "AccountFilterBar"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "OriginalPathFilterBar"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "SelectedAssetsActionBar"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "MoveSelectedGroupsDialog"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "combinedClickable"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "LaunchedEffect\(projectState\.activeProjectId, inboxQuery, selectedPhotoCollection\)"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "onMoveProjectGroup"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectUiModels.kt" "groupMoveTargets"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" (U @(0x5168,0x90E8,0x8D26,0x53F7))
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" (U @(0x5168,0x90E8,0x8DEF,0x5F84))
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "SourceFilterBar"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "PhotoDetailScreen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "LazyVerticalGrid"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "GridCells\.Fixed\(gridColumnCount\)"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\SettingsScreen.kt" "GridColumnToggle"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "CompactPhotoTile"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "storageGateway\.persistProjectPhotoGridColumnCount"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "compactFallback"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "BackHandler"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "stateDescription"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "contentDescription = `"照片"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\SettingsScreen.kt" (U @(0x0032,0x5217))
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\SettingsScreen.kt" (U @(0x0033,0x5217))
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "PhotoInfoCard"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "ReceiverHeroControl"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "PhotoPreview"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "ThumbnailPreviewMemoryCache"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "LruCache<String, Bitmap>"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "thumbnailPreviewCacheKey"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "FilterToggleRow"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "loadPreviewBitmap"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "BitmapFactory"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "thumbnailBitmap"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "readRawTiffOrientation"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "TIFF_ORIENTATION_TAG"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "isRawPreviewLocation"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" 'endsWith\("\.nef"\)'
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "FullScreenPhotoPreview"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "ImmersiveSystemBars"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "ContentScale.Fit"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "detectTapGestures"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "rememberTransformableState"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "FULLSCREEN_MAX_SCALE"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "PreviewQuality.Detail"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "PreviewQuality.FullScreen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "PREVIEW_DETAIL_MAX_DIMENSION_PX"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "PREVIEW_FULLSCREEN_MAX_DIMENSION_PX"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "fitToImageAspect = true"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "FilterQuality.High"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "decodeFullBitmap"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "isJpegPreviewLocation"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "isMediaStoreImageUri"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "content://media/"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "PhotoMetadata"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "loadPhotoMetadata"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "TAG_PHOTOGRAPHIC_SENSITIVITY"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "rememberScrollState"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "verticalScroll"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "加载中"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "RAW 预览待生成"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "decodeLargestEmbeddedJpeg"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\media\CameraPreviewMedia.kt" "findEmbeddedJpegRanges"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "Image\("
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\AccountsScreen.kt" "AccountMenuRow"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "CONTINUOUS_INBOX_LIMIT = 2_000"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "limit = CONTINUOUS_INBOX_LIMIT"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectUiModels.kt" "GlobalDestination"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectUiModels.kt" "ProjectDestination"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectUiModels.kt" "ScoreFilter"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectUiModels.kt" "ProjectPhotoCollection"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "ProjectPhotoCollectionBar"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectUiModels.kt" "ProjectDestination\.Inbox"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectUiModels.kt" "ProjectDestination\.Transfers"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectUiModels.kt" "ProjectDestination\.Publish"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "ProjectSwitcherDialog"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "TransfersScreen"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "PublishQueueScreen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "AccountsScreen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "DiagnosticsScreen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "ReceiverSettings"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "saveReceiverSettings\(settings\)"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "onSaveDeviceAccount"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "ProjectReceiverLaunchPanel"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\AccountsScreen.kt" "AccountDetailScreen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\SettingsScreen.kt" "SettingsScreen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ReviewModeScreen.kt" "ReviewModeScreen"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\ReceiverDefaults.kt" "192\.168\.50\.1"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\ProjectAssetsScreen.kt" "AccountFilterBar"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "DetailLine"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "rawPath"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "jpegPath"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "previewLocation"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "bestScore"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "highlightClippingPenalty"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\AssetUiModels.kt" "qualitySignalRows"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\ui\PhotoDetailScreen.kt" "QualitySignalStrip"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "reviewQueue"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "loadSelects"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "storage_location"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "projectSelectsAssetGroupPageJson"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" '"best_score"'
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" '"review_queue"'
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" '"strategy_profile_id"'
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" "projectSelectsAssetGroupPageJson"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "RAW \\+ JPEG"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" "FormatGroupSection"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" '"Overview"'
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" '"Start"'
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\ui\CameraConnectorApp.kt" '"No imported assets yet\."'
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "password: String\?"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "activeConnections"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "latestPort"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "lastSeenAtMs"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "authMode"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "accountCount"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "renameProject"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "moveProjectGroup"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "acceptRecommendedBest"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGateway.kt" "markBurstNeedsReview"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGatewayFactory.kt" "BuildConfig\.USE_NATIVE_CORE"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGatewayFactory.kt" "NativeCoreGateway"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGatewayFactory.kt" "ReceiverServiceController"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGatewayFactory.kt" '"inbox"'
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\CoreGatewayFactory.kt" "saveAndroidReceiverPaths"
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" "saveAndroidReceiverDefaults"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" 'System\.loadLibrary\("camera_connector_ffi"\)'
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" "NativeEnvelope"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" '"state_dir"'
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" '"defer_publish"'
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" "renameProjectJson"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" "moveProjectGroupJson"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" "acceptRecommendedBestJson"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" "markBurstNeedsReviewJson"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" "startReceiverJson"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeMobileCore.kt" "stopReceiverJson"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "class NativeCoreGateway"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "CoreGateway"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "nativeCore.renameProject"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "nativeCore.moveProjectGroup"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "nativeCore.acceptRecommendedBest"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "nativeCore.markBurstNeedsReview"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "splitHostAndPort"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "pollDashboard"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "recent_failures"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "assets: JSONObject"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" '"Completed"'
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "active_connections"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "last_remote_port"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "last_seen_at_ms"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "auth_mode"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "account_count"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "isNull"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "virtual_display_path"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" '"error"'
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "gatewayScope\.cancel"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "password = password"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "receiverServiceController\.startReceiver"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\core\NativeCoreGateway.kt" "receiverServiceController\.stopReceiver"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "ACTION_START"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "ACTION_STOP"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "NativeMobileCore"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "AndroidPublishWorker"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "AndroidStorageGateway"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "SafPublishTarget"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "PUBLISH_QUEUE_POLL_INTERVAL_MS"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "PendingIntent"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "setContentIntent"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "\.addAction\(.*(Stop|$(U @(0x505C,0x6B62)))"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "FLAG_IMMUTABLE"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "CameraConnectorReceiver"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "Log\.i"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" "Log\.e"
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" (U @(0x76F8,0x673A,0x8FDE,0x63A5,0x5668))
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" (U @(0x6B63,0x5728,0x542F,0x52A8,0x63A5,0x6536,0x670D,0x52A1))
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" (U @(0x505C,0x6B62))
Assert-Contains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" (U @(0x63A5,0x6536,0x670D,0x52A1,0x72B6,0x6001))
Assert-NotContains "apps\android\app\src\main\java\com\cameraconnector\app\service\ReceiverForegroundService.kt" '"Starting receiver"'
Assert-Contains "apps\android\app\src\main\AndroidManifest.xml" "@string/app_name"
Assert-Contains "scripts\install_android_debug.ps1" "verify_android_build\.ps1"
Assert-Contains "scripts\install_android_debug.ps1" "adb"
Assert-Contains "scripts\install_android_debug.ps1" "install"
Assert-Contains "scripts\install_android_debug.ps1" "InstallTimeoutSeconds"
Assert-Contains "scripts\install_android_debug.ps1" "WaitForExit"
Assert-Contains "scripts\install_android_debug.ps1" '\$install\.Refresh\(\)'
Assert-Contains "scripts\install_android_debug.ps1" '\$install\.ExitCode -ne \$null -and \$install\.ExitCode -ne 0'
Assert-Contains "scripts\install_android_debug.ps1" 'Failure \\\['
Assert-Contains "scripts\install_android_debug.ps1" "failed to install"
Assert-Contains "scripts\install_android_debug.ps1" "INSTALL_FAILED"
Assert-Contains "scripts\install_android_debug.ps1" "monkey"
Assert-Contains "scripts\install_android_debug.ps1" "com\.cameraconnector\.app"
Assert-Contains "scripts\verify_android_build.ps1" "inspect_android_apk\.ps1"
Assert-Contains "scripts\verify_android_build.ps1" "cameraConnector\.useNativeCore=true"
Assert-Contains "scripts\build_android_native.ps1" "x86_64-linux-android"
Assert-Contains "scripts\build_android_native.ps1" "arm64-v8a"
Assert-Contains "scripts\build_android_native.ps1" "x86_64"
Assert-Contains "scripts\inspect_android_apk.ps1" "lib/arm64-v8a/libcamera_connector_ffi\.so"
Assert-Contains "scripts\inspect_android_apk.ps1" "lib/x86_64/libcamera_connector_ffi\.so"
Assert-Contains "scripts\inspect_android_apk.ps1" "Get-FileHash"
Assert-Contains "scripts\inspect_android_apk.ps1" "AndroidManifest\.xml"
Assert-Contains "scripts\inspect_android_apk.ps1" "classes\.dex"
Assert-Contains "scripts\inspect_android_apk.ps1" "android-apk-report"
Assert-Contains "scripts\preflight_android_device.ps1" "ro\.build\.version\.sdk"
Assert-Contains "scripts\preflight_android_device.ps1" "ro\.product\.cpu\.abilist"
Assert-Contains "scripts\preflight_android_device.ps1" "x86_64"
Assert-Contains "scripts\preflight_android_device.ps1" "ip addr"
Assert-Contains "scripts\preflight_android_device.ps1" "POST_NOTIFICATIONS"
Assert-Contains "scripts\preflight_android_device.ps1" "android-device-preflight"
Assert-Contains "scripts\start_android_emulator.ps1" "CameraConnector_API36"
Assert-Contains "scripts\start_android_emulator.ps1" "sys\.boot_completed"
Assert-Contains "scripts\start_android_emulator.ps1" "InstallAfterBoot"
Assert-Contains "scripts\start_android_emulator.ps1" "install_android_debug\.ps1"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "USER"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "PASS"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "EPSV"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "STOR"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "RealAssetDirectory"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "RealPairLimit"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "Find-RealRawJpegPairs"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "EDGE_JPG_ONLY"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "EDGE_RAW_ONLY"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "EDGE_DUPLICATE"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "EDGE_NOT_IMAGE"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "transfer-log\.jsonl"
Assert-Contains "scripts\verify_android_emulator_ftp_upload.ps1" "password_hash"
Assert-Contains "scripts\smoke_android_device.ps1" "preflight_android_device\.ps1"
Assert-Contains "scripts\prepare_android_real_camera_test.ps1" "preflight_android_device\.ps1"
Assert-Contains "scripts\prepare_android_real_camera_test.ps1" "smoke_android_device\.ps1"
Assert-Contains "scripts\prepare_android_real_camera_test.ps1" "android-real-camera-test\.md"
Assert-Contains "apps\android\README.md" "prepare_android_real_camera_test\.ps1"
Assert-Contains "scripts\collect_android_diagnostics.ps1" "adb"
Assert-Contains "scripts\collect_android_diagnostics.ps1" "devices"
Assert-Contains "scripts\collect_android_diagnostics.ps1" "dumpsys package"
Assert-Contains "scripts\collect_android_diagnostics.ps1" "dumpsys activity services"
Assert-Contains "scripts\collect_android_diagnostics.ps1" "logcat"
Assert-Contains "scripts\collect_android_diagnostics.ps1" "CameraConnectorReceiver"
Assert-Contains "scripts\smoke_android_device.ps1" "install_android_debug\.ps1"
Assert-Contains "scripts\smoke_android_device.ps1" "collect_android_diagnostics\.ps1"
Assert-Contains "scripts\smoke_android_device.ps1" "SkipInstall"
Assert-Contains "scripts\smoke_android_device.ps1" "pm path"
Assert-Contains "scripts\smoke_android_device.ps1" "POST_NOTIFICATIONS"
Assert-Contains "scripts\smoke_android_device.ps1" "monkey"
Assert-Contains "scripts\smoke_android_device.ps1" "logcat -c"
Assert-Contains "scripts\smoke_android_device.ps1" "pidof"
Assert-Contains "scripts\smoke_android_device.ps1" "Collect-Diagnostics"
Assert-Contains "scripts\smoke_android_device.ps1" "com\.cameraconnector\.app"
Assert-Contains "docs\product\android-app-architecture.md" "Kotlin \+ Jetpack Compose"
Assert-Contains "docs\product\android-app-architecture.md" "Rust core"

Write-Host "Android skeleton checks passed."
